# Generated by Django 5.2.8 on 2025-11-20 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_booking_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=400)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.flight')),
            ],
            options={
                'verbose_name': 'Annulation',
                'verbose_name_plural': 'Annulations',
                'ordering': ['reason'],
            },
        ),
    ]
