# Generated by Django 5.2.8 on 2025-11-20 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_annulation'),
    ]

    operations = [
        migrations.AddField(
            model_name='annulation',
            name='passenger',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='flights.passenger'),
        ),
    ]
