# Generated by Django 5.2.8 on 2025-11-23 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_annulation_passenger'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annulation',
            options={'ordering': ['id_annulation'], 'verbose_name': 'Annulation', 'verbose_name_plural': 'Annulations'},
        ),
        migrations.AddField(
            model_name='annulation',
            name='id_annulation',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
