# Generated by Django 5.2.8 on 2025-11-24 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_alter_annulation_options_annulation_id_annulation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annulation',
            name='flight',
        ),
        migrations.AddField(
            model_name='annulation',
            name='booking',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='flights.booking', verbose_name='Reservation'),
        ),
        migrations.AddField(
            model_name='annulation',
            name='date_annulation',
            field=models.DateField(auto_now_add=True, null=True, verbose_name="Date d'annulation"),
        ),
        migrations.AlterField(
            model_name='annulation',
            name='id_annulation',
            field=models.IntegerField(default=0, unique=True, verbose_name='ID Annulation'),
        ),
        migrations.AlterField(
            model_name='annulation',
            name='passenger',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='flights.passenger', verbose_name='Passager'),
        ),
        migrations.AlterField(
            model_name='annulation',
            name='reason',
            field=models.CharField(max_length=400, verbose_name='Raison'),
        ),
    ]
