# Generated by Django 5.2.8 on 2025-11-24 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0006_remove_annulation_flight_annulation_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annulation',
            name='booking',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flights.booking', verbose_name='Reservation'),
        ),
    ]
