# Generated by Django 5.2.8 on 2025-11-24 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0007_alter_annulation_booking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annulation',
            options={'verbose_name': 'Annulation', 'verbose_name_plural': 'Annulations'},
        ),
        migrations.RemoveField(
            model_name='annulation',
            name='id_annulation',
        ),
    ]
